version: 4.0.{build}
branches:
  except:
    - gh-pages
    - ubuntu-ci
    - win-ci
    - wsl-ci
skip_tags: true
image: macos
environment:
  APPVEYOR_SSH_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOgZaR7bVAJCsBs/yDlzNbHTvhicc1C7SeyEuVwN+Q0l
#init:
#  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
build_script:
- sh: |
    uname -a
    curl https://download.visualstudio.microsoft.com/download/pr/62f78047-71de-460e-85ca-254f1fa848de/ecabeefdca2902f3f06819612cd9d45c/dotnet-sdk-6.0.100-osx-x64.tar.gz -o dotnet-sdk-6.0.100-osx-x64.tar.gz
    DOTNET_FILE=dotnet-sdk-6.0.100-osx-x64.tar.gz
    export DOTNET_ROOT=$(pwd)/dotnet
    mkdir -p "$DOTNET_ROOT" && tar zxf "$DOTNET_FILE" -C "$DOTNET_ROOT"
    export PATH=$PATH:$DOTNET_ROOT
    sudo rm -rf /usr/local/share/dotnet
    sudo mv dotnet /usr/local/share
    dotnet --version
#- dotnet build src/SIPSorcery.sln --framework netcoreapp3.1
test_script:
# TODO: Track down why macos fails to determine the local interface for IPv6 destinations on approx. every second test run.
#       possibly to do with different vm configs but same thing is happening on both appveyor and GitHub Actions CI's.
- dotnet test test/unit/SIPSorcery.UnitTests.csproj -c Release --framework net6.0
#on_finish:
#  - sh: export APPVEYOR_SSH_BLOCK=true
#  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

